DROP TABLE IF EXISTS equipment_movement CASCADE;
DROP TABLE IF EXISTS maintenance CASCADE;
DROP TABLE IF EXISTS warehouse_equipment CASCADE;
DROP TABLE IF EXISTS order_equipment CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS equipment CASCADE;
DROP TABLE IF EXISTS equipment_type CASCADE;
DROP TABLE IF EXISTS supplier CASCADE;
DROP TABLE IF EXISTS warehouse CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS position CASCADE;

DROP TYPE IF EXISTS equipment_maintenance_type CASCADE;
DROP TYPE IF EXISTS type_equipment_status CASCADE;
DROP TYPE IF EXISTS type_sex CASCADE;